# Stage 1: build React app
FROM node:18-alpine AS build_react

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/. .
RUN npm run build

# Stage 2: serve with nginx
FROM nginx:alpine AS run_frontend

# COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build_react /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

