FROM python:3.11-slim AS build_fastapi

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY . /app

EXPOSE 8000

CMD ["sh", "-c", "python /app/wait_for_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"]
